SELECT COUNT(*) FISH_COUNT, MAX(A.LENGTH) MAX_LENGTH, A.FISH_TYPE
FROM (
    SELECT ID, FISH_TYPE, IF(LENGTH<=10, 10, IFNULL(LENGTH, 10)) LENGTH, TIME
    FROM FISH_INFO
) A
GROUP BY A.FISH_TYPE
HAVING SUM(A.LENGTH)/COUNT(*) >= 33
ORDER BY A.FISH_TYPE 
